### ISSUE TITLE
Black Screen, really slow system after launch.

### ISSUE THREAD

**Issue by Pesoen** [rsn8887/OpenRCT2#3]
**OS:** Horizon OS 10.2.0|AMS 0.15.sS
**Version:** 1.05
**Commit/Build:** b0769ea

when i try to launch openrct2 on my switch, i just get a black screen, and system respons is really slow. if i click the home button, or any other button, it takes about 24 seconds before its registered. it keeps a black screen despite having left it about 15 minutes at this point. not sure if there is a log file i can look at, but i have yet to find any.

**Steps to reproduce:**
1. Download the build from github.
2. extract to my switch folder on my sd card.
3. copy a legit RCT2 install to the correct folder, making sure the paths are correct(/switch/openrc2/rct2(landscapes etc)
4. launch the game.

**Comment by Pesoen** [comment]
any help at all? really would love to play rct2 on the go..

**Comment by ghost** [comment]
Gog.com version seems to have the best compatibility, are you using Atmosphere? Fat32?

**Comment by Pesoen** [comment]
Latest Atmosphere, Fat32, and the GOG version and an original disk version. all result in a black screen, that seems to load forever, since it slows the entire system down.

**Comment by rsn8887** [comment]
I am also on 10.2 now, still works for me.

Probably something wrong with your files. You need to make sure you force binary transfer mode for all files if you use ftp. Also make sure none of the folders has archive bit set. 

PM me on gbatemp forums and I might be able to help more.

**Comment by rsn8887** [comment]
Also make sure you are not launching via ALBUM you have to launch by holding R over a GAME. Never launch homebrew via album it doesn’t give enough memory.

**Comment by Pesoen** [comment]
i have now updated to HOS 11.0.1 and atmosphere 0.18.0 is still not working.

gonna try copying the files over again, but with the "force binary" thingy(if i can find that in winscp) or just take out the card and transfer it directly.. that should work right?

**Comment by Pesoen** [comment]
okay, tried transferring it in binary mode, and removing archive bits. still just a black screen, coming up on 15 minutes. where does it create the cache files? want to see if it actually does anything, or if it just stops somewhere specific.

**Comment by Pesoen** [comment]
okay, progress, i now have a log and err.txt, gonna let it run over night in the dock, see if it works in the morning, it gets stuck at 1227 if i connect to the ftp on it. so gonna just leave it running, will see tomorrow if it can get past 1227.

**Comment by Pesoen** [comment]
leaving it overnight worked, now it's in the main menu :) thanks for all the help, i suspect the binary transfer and removal of archive bit was what did it, but i don't know.. but after using the binary transfer, i got an err.txt and a log.txt file, so that's why i suspect that was it..
