### ISSUE TITLE
Game crashes on 12.0.1|AMS M.19.1|E

### ISSUE THREAD

**Issue by CleoTheBirb** [rsn8887/OpenRCT2#5]
Game wont run, everything is set up correctly, just gives a general "Software closed due to an error".

**Comment by rsn8887** [comment]
Nothing in the code is firmware specific like that. If it works on one version, it should work on all.

Are you sure you didn’t change anything to your openrct install when you updated your cfw? In other words, did it work for you before?

Note when transferring data files via ftp, you have to force binary transfer mode.

Also make sure you launch via game not via album.

**Comment by CleoTheBirb** [comment]
I just got into modding my switch, so this was my first install of the game. I didn't FTP, and i've been launching via game. Might have something to do with emuMMC?

**Comment by rsn8887** [comment]
Can you PM me on gbatemp forums?

There seems to be incompatibility on fw 12 with all homebrew built before December 2019. I will try to rebuilt and make a new release soon.

**Comment by CleoTheBirb** [comment]
I just made a gbatemp account, but it wont let me PM. do you have a discord or something?

**Comment by rsn8887** [comment]
Yes I am on Discord on the classicgaming Server for example.
